import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import './globals.css';

import dynamic from 'next/dynamic';
import { Toaster } from '@/components/ui/toaster';
const Providers = dynamic(() => import('@/components/Providers'), {
  ssr: false,
});
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'next-qa',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='zh-Hant'>
      <body className={cn(inter.className, 'min-h-screen pt-16 antialiased')}>
        <Providers>
          <Navbar />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
